### ISSUE TITLE
transplant SharedMemoryManager to python3.6

### ISSUE THREAD

**Issue by JialeDeng** [TracelessLe/shared_numpy#1]
hi there, I am confused by this problem recently, and thanks for your blog !!
But is there any chance to transplant SharedMemoryManager to python3.6? Thanks a lot!

**Comment by TracelessLe** [comment]
I don't do the transplant you need before. In my opinion, it is possible to transplant SharedMemoryManager to python 3.7/3.6. You can try to compare the source code implement of SharedMemoryManager in python 3.8 and python 3.7/3.6 (such as in py38/lib/python3.8/multiprocessing/managers.py), and make some modify to python3.6 multiprocessing module source code.

<img width="1194" alt="2021-04-06 09 59 03" src="https://user-images.githubusercontent.com/22371026/113648176-c51e9300-96be-11eb-8b2a-b7930eae939e.png">

**Comment by JialeDeng** [comment]
Thanks, I am also trying this way! 👍
